export type { StorageAdapter } from './StorageAdapter'
export type { WallCalData, DayEntry, UserSettings, MigrationResult, MarkType, Note, DayColor } from './types'
export { createEmptyData, mergeData, DAY_COLOR_PALETTE } from './types'
export { LocalStorageAdapter, localStorageAdapter } from './LocalStorageAdapter'
export { FirestoreAdapter } from './FirestoreAdapter'
export { persistenceService } from './PersistenceService'
